name: "Workflow for event"

on:
    push:
        branches:
            - master
            - test
    workflow_dispatch:

jobs:
    on-push:
        runs-on: windows-latest
        steps:
            - name: "Running on master/test branch when push event is triggered."
              run: echo "Running on master/test branch when push event is triggered.
    
    on-workflow-dispatch:
        if: ${{ github.event_name == 'workflow_dispatch' }}
        runs-on: windows-latest
        steps:
          - name: "Running on master/test branch when workflow dispatch event is triggered."
            run: echo "Running on master/test branch when workflow dispatch event is triggered."